# Generated by Django 4.2.1 on 2023-05-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site', models.TextField(max_length=255)),
                ('data_cotacao', models.DateField()),
                ('link_imagem', models.TextField(default='https://placehold.jp/3d4070/ffffff/150x150.png', max_length=500)),
            ],
        ),
    ]
